import { z } from 'zod';

export const serviceHealthSchema = z.object({
  status: z.literal('ok'),
  service: z.string().min(1),
});

export type ServiceHealth = z.infer<typeof serviceHealthSchema>;

export {
  capacityCollectionResultSchema,
  capacityErrorSchema,
  capacityFreshnessSchema,
  capacityKindSchema,
  capacityCurrentProviderSchema,
  capacityCurrentResponseSchema,
  capacityHistoryResponseSchema,
  capacityProviderHealthSchema,
  capacityResourceSchema,
  capacitySnapshotSchema,
  capacitySourceSchema,
  capacityStatusSchema,
  capacityTimestampSchema,
  capacityUnitSchema,
  type CapacityCollectionResult,
  type CapacityCurrentProvider,
  type CapacityCurrentResponse,
  type CapacityError,
  type CapacityFreshness,
  type CapacityHistoryResponse,
  type CapacityKind,
  type CapacityProviderHealth,
  type CapacityResource,
  type CapacitySnapshot,
  type CapacitySource,
  type CapacityStatus,
  type CapacityUnit,
} from './capacity.js';

export {
  AGENT_HEARTBEAT_INTERVAL_MS,
  AGENT_MAX_MESSAGE_BYTES,
  AGENT_PROTOCOL_VERSION,
  agentClientMessageSchema,
  agentActionAcceptedSchema,
  agentActionKindSchema,
  agentActionRequestSchema,
  agentActionResultSchema,
  agentActionResultStatusSchema,
  agentHeartbeatSchema,
  agentHelloAcceptedSchema,
  agentHelloSchema,
  agentProtocolErrorSchema,
  agentServerMessageSchema,
  actionDenialReasonSchema,
  actionErrorCodeSchema,
  actionErrorSchema,
  machineActionCatalogSchema,
  machineActionInputSchema,
  machineActionResponseSchema,
  machineActionRecordSchema,
  machineActionStatusSchema,
  machineActionsResponseSchema,
  machineArchitectureSchema,
  machineCapabilitySchema,
  machineConnectionStatusSchema,
  machineIdentitySchema,
  machinePlatformSchema,
  machineProtocolVersionSchema,
  machineSummarySchema,
  machineTelemetrySchema,
  machinesResponseSchema,
  repoStatusResultSchema,
  repositoryActionTargetSchema,
  serviceActionTargetSchema,
  serviceRestartActionSchema,
  serviceRestartResultSchema,
  type ActionDenialReason,
  type ActionError,
  type ActionErrorCode,
  type AgentActionAccepted,
  type AgentActionKind,
  type AgentActionRequest,
  type AgentActionResult,
  type AgentActionResultStatus,
  type AgentClientMessage,
  type AgentHeartbeat,
  type AgentHello,
  type AgentHelloAccepted,
  type AgentProtocolError,
  type AgentServerMessage,
  type MachineActionCatalog,
  type MachineActionInput,
  type MachineActionRecord,
  type MachineActionStatus,
  type MachineActionsResponse,
  type MachineCapability,
  type MachineConnectionStatus,
  type MachineArchitecture,
  type MachineIdentity,
  type MachinePlatform,
  type MachineSummary,
  type MachineTelemetry,
  type MachinesResponse,
  type RepoStatusResult,
  type RepositoryActionTarget,
  type ServiceActionTarget,
  type ServiceRestartAction,
  type ServiceRestartResult,
} from './agent.js';

export {
  attentionLabelSchema,
  ciStateSchema,
  githubCiSummarySchema,
  githubFreshnessSchema,
  githubIssueSummarySchema,
  githubPullRequestSummarySchema,
  githubRepositorySnapshotSchema,
  gitHubSourceHealthSchema,
  gitHubWebhookEnvelopeSchema,
  gitHubWebhookDeliveryOutcomeSchema,
  gitHubWebhookDeliveryRecordSchema,
  gitHubWebhookHealthSchema,
  projectAttentionSummarySchema,
  projectConfigSchema,
  projectDescriptionSchema,
  projectDetailResponseSchema,
  projectDetailSchema,
  projectDisplayNameSchema,
  projectIdSchema,
  projectOwnerSchema,
  projectRepoNameSchema,
  projectRepositoryConfigSchema,
  projectRepositorySummarySchema,
  projectsConfigFileSchema,
  projectsResponseSchema,
  projectSummarySchema,
  type AttentionLabel,
  type CiState,
  type GitHubCiSummary,
  type GitHubFreshness,
  type GitHubIssueSummary,
  type GitHubPullRequestSummary,
  type GitHubRepositorySnapshot,
  type GitHubSourceHealth,
  type GitHubWebhookEnvelope,
  type GitHubWebhookDeliveryOutcome,
  type GitHubWebhookDeliveryRecord,
  type GitHubWebhookHealth,
  type ProjectAttentionSummary,
  type ProjectConfig,
  type ProjectDetail,
  type ProjectDetailResponse,
  type ProjectId,
  type ProjectRepositoryConfig,
  type ProjectRepositorySummary,
  type ProjectsConfigFile,
  type ProjectsResponse,
  type ProjectSummary,
} from './projects.js';
