import { z } from 'zod';

export const serviceHealthSchema = z.object({
  status: z.literal('ok'),
  service: z.string().min(1),
});

export type ServiceHealth = z.infer<typeof serviceHealthSchema>;

export {
  capacityCollectionResultSchema,
  capacityErrorSchema,
  capacityFreshnessSchema,
  capacityKindSchema,
  capacityCurrentProviderSchema,
  capacityCurrentResponseSchema,
  capacityHistoryResponseSchema,
  capacityProviderHealthSchema,
  capacityResourceSchema,
  capacitySnapshotSchema,
  capacitySourceSchema,
  capacityStatusSchema,
  capacityTimestampSchema,
  capacityUnitSchema,
  type CapacityCollectionResult,
  type CapacityCurrentProvider,
  type CapacityCurrentResponse,
  type CapacityError,
  type CapacityFreshness,
  type CapacityHistoryResponse,
  type CapacityKind,
  type CapacityProviderHealth,
  type CapacityResource,
  type CapacitySnapshot,
  type CapacitySource,
  type CapacityStatus,
  type CapacityUnit,
} from './capacity.js';

export {
  AGENT_HEARTBEAT_INTERVAL_MS,
  AGENT_MAX_MESSAGE_BYTES,
  AGENT_PROTOCOL_VERSION,
  agentClientMessageSchema,
  agentHeartbeatSchema,
  agentHelloAcceptedSchema,
  agentHelloSchema,
  agentProtocolErrorSchema,
  agentServerMessageSchema,
  machineArchitectureSchema,
  machineCapabilitySchema,
  machineConnectionStatusSchema,
  machineIdentitySchema,
  machinePlatformSchema,
  machineSummarySchema,
  machineTelemetrySchema,
  machinesResponseSchema,
  type AgentClientMessage,
  type AgentHeartbeat,
  type AgentHello,
  type AgentHelloAccepted,
  type AgentProtocolError,
  type AgentServerMessage,
  type MachineCapability,
  type MachineConnectionStatus,
  type MachineArchitecture,
  type MachineIdentity,
  type MachinePlatform,
  type MachineSummary,
  type MachineTelemetry,
  type MachinesResponse,
} from './agent.js';
